config/routes.rb
DeviseOmniauth::Application.routes.draw do

  #tell Devise in which controller we will implement Omniauth callbacks
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks" }

  ########### For Twitter ##################
  get '/fetch_email_from_twitter/:twitter_uid' => "users/fetch_email#fetch_email_from_twitter" , :as => :fetch_email_from_twitter
  post 'fetch_email_from_twitter_and_create' => "users/fetch_email#fetch_email_from_twitter_and_create" , :as => :fetch_email_from_twitter_and_create
  match "/confirm_twitter/:token/:twitter_uid"=>"users/fetch_email#confirm_twitter",:as=>:confirm_twitter

  ########## For Linked In ##################
  get '/fetch_email_from_linkedin/:linkedin_uid' => "users/fetch_email#fetch_email_from_linkedin" , :as => :fetch_email_from_linkedin
  post 'fetch_email_from_linkedin_and_create' => "users/fetch_email#fetch_email_from_linkedin_and_create" , :as => :fetch_email_from_linkedin_and_create
  match "/confirm_linkedin/:token/:linkedin_uid"=>"users/fetch_email#confirm_linkedin",:as=>:confirm_linkedin

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  get "home/index"
  root :to => "home#index"
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Omniauth" %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>
</head>
<body>
<div id="container">
  <div align="right">
    <% if user_signed_in? %>
        singned in as <i><%= current_user.email %></i>  |
        <%= link_to('Edit registration', edit_user_registration_path) %> |
        <%= link_to('Logout', logout_path, :method => :delete) %>
    <% else %>
        <%= link_to('Login', login_path)  %> |
        <%= link_to('Register', new_user_registration_path)  %>
    <% end %>
  </div>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= content_tag :h1, yield(:title) if show_title? %>
  <%= yield %>
</div>
</body>
</html>